/*
 * Router Manager
 *
 * This is a managing network service.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Power string

// List of Power
const (
	SHUTDOWN Power = "shutdown"
	REBOOT Power = "reboot"
)
